language: python

jobs:
  include:
    - os: linux
      dist: jammy
      python: "3.11"
    - os: linux
      dist: jammy
      python: "nightly"

install:
  - source .envrc
  - echo $URL_COUNTAPI
  - make requirements
  - pip3 install codecov

script:
  - coverage run -m pytest
  - coverage xml

after_success:
  - codecov

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key:
    secure: rRMayW6X4p7yEldyfHu9pEDzZRMoZaudo29WPUxJqrg2qrSPV8jdBlMUgFlulatYEPTNXjONO09ZQWSXZ3RQ7MkH22/CIEbkT2KADWwxZu/oD09VM1NeKR5uW2q0ZSCigU6J08gxO7fJiBor+bqIaxx7eMebpQVjQ+MpbWH/eAz94fuksFPEzhFDIhXOUMKP9Y5NB99Nn2aLjPv4zvV4a0ODzYdJ8mQpnp141NYqHmPxZmv+UQ+LuoLIkmkRn+Zf1D98YT2pJE/FztWCYGzuyJllujl+MFc4+x1K1GASEUGN6IddDCc+TeyrIyOh2VxIoREUsmqqjBdSq5eDaj0k5cVJXnaXHIFJdzwd7xZn+qzI7/V4kXcAxzuhgtO7sT7X/uqinwKq1mwh8yPPgcad8vn1i+ZKE5n3Gms11IGyXnq2u+RPALy6hxinm1NJrPQHawJavmlBMMql5j28a6YmqUCP4gAdroE+NtEuAb3DOtNa6iwg7zUtz6L5z8uJGaVx/tkVelJYoZTnySySkiBQNLqV3uEmDk1h/mgeWMIJiVd3eyJPlkItL6GJICiAwQnU4ju3qnbY+7TO4xVjIpUwroa9G0YPJV9YbovueIUwGl9wQPsCL6E6OCSGUiy7FrZ2yctxRUrLiPx2qaAfwNKLwoNBnJg0cigmOSro7pNm4bA=
  on:
    all_branches: true
    tags: true
